title: Eric Chubaty
description: "Eric Chubaty"
author:
  name: "Eric Chubaty"
  email: "eric@chubaty.dev"
  url: "https://chubaty.dev"
linkedin: "https://www.linkedin.com/in/echubaty"
tryhackme: "https://tryhackme.com/p/echubaty"
github: "https://github.com/echubaty"


baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Eric Chubaty"
year : "2023"
